volumes:
  certbot_ssl:

services:
  certbot:
    image: ${CERTBOT_IMAGE:-certbot/certbot}
    ports:
      - 80:80
    volumes:
      - certbot_ssl:/etc/letsencrypt
      - ./nginx/html:/var/www/html/.html:ro
    command: certonly --standalone --email $CERTBOT_EMAIL -d $CERTBOT_DOMAIN --cert-name=certfolder --key-type rsa --agree-tos --non-interactive && chmod 777 -R /etc/letsencrypt