services:
  certbot:
    image: ${CERTBOT_IMAGE}
    ports:
      - 80:80
    volumes:
      - certbot_ssl:/etc/letsencrypt
      - ./nginx/html:/var/www/html/.html:ro
    entrypoint: >
      sh -c "
      certbot certonly --standalone --email $CERTBOT_EMAIL -d $CERTBOT_DOMAIN --cert-name=certfolder --key-type rsa --agree-tos --non-interactive
      && chmod -R 644 /etc/letsencrypt/live/
      && chmod -R 644 /etc/letsencrypt/archive/
      "