volumes:
  cleaner_logs:

services:
  cleaner:
    extends:
      file: ./parents.yml
      service: custom_service
    build:
      target: cleaner
    volumes:
      - web_server_files:/cleaner
      - cleaner_logs:/logs
    environment:
      - CLEANER_DIR=${CLEANER_DIR:-/cleaner}
    networks:
      - cron_to_cleaner