volumes:
  db_data:

services:
  db:
    extends:
      file: ./parents.yml
      service: parent
    image: ${DB_IMAGE:-postgres:17-alpine}
    user: postgres
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-qwerty}
      - POSTGRES_DB=${DB_NAME:-bot}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - ${DB_EXTERNAL_PORT:-127.0.0.1:5432}:5432
    networks:
      - bot_to_db
      - downloader_to_db