volumes:
  nginx_files:
  certbot_ssl:

services:
  nginx:
    extends:
      file: ./parents.yml
      service: parent
    image: ${NGINX_IMAGE}
    user: nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/html:/html/.html:ro
      - certbot_ssl:/etc/nginx/ssl/:ro
      - nginx_files:/uploads:ro
    ports:
      - ${NGINX_HTTPS_PORT}:443
      - ${NGINX_HTTP_PORT}:80
    networks:
      - default