services:
  parent:
    restart: ${CONTAINER_RESTART}
    stop_signal: SIGINT
    cap_drop:  
      - ALL
    cap_add:  
      - NET_BIND_SERVICE  
    security_opt:  
      - no-new-privileges:true
      - seccomp:unconfined
    deploy:  
      resources:
        limits:
          cpus: ${CONTAINER_CPUS_LIMIT}
          memory: ${CONTAINER_MEMORY_LIMIT}
    ulimits:  
      nproc: 1024
      nofile:  
        soft: 1024
        hard: 2048
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  custom_service:
    extends:
      file: ./parents.yml
      service: parent
    build:
      context: ..
      args:
        - RUNNER_IMAGE=${RUNNER_IMAGE}
    user: runner
