services:
  parent:
    restart: ${CONTAINER_RESTART:-always}
    cap_drop:  
      - ALL
    cap_add:  
      - NET_BIND_SERVICE  
    security_opt:  
      - no-new-privileges:true
      - seccomp:unconfined
    deploy:  
      resources:
        limits:
          cpus: ${CONTAINER_CPUS_LIMIT:-1.0}
          memory: ${CONTAINER_MEMORY_LIMIT:-512M}
    ulimits:  
      nproc: 1024
      nofile:  
        soft: 1024
        hard: 2048
  custom_service:
    extends:
      file: ./parents.yml
      service: parent
    environment:
      - LOGS_DIR=/logs
      - TMP_DIR=-/tmp
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-bot}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-qwerty}
      - CACHE_HOST=cache
      - CACHE_PORT=6379
      - CACHE_PASSWORD=${CACHE_PASSWORD:-qwerty}

