services:
  parent:
    restart: ${CONTAINER_RESTART:-always}
    stop_signal: SIGINT
    cap_drop:  
      - ALL
    cap_add:  
      - NET_BIND_SERVICE  
    security_opt:  
      - no-new-privileges:true
      - seccomp:unconfined
    deploy:  
      resources:
        limits:
          cpus: ${CONTAINER_CPUS_LIMIT:-1.0}
          memory: ${CONTAINER_MEMORY_LIMIT:-512M}
    ulimits:  
      nproc: 1024
      nofile:  
        soft: 1024
        hard: 2048
  custom_service:
    extends:
      file: ./parents.yml
      service: parent
    build:
      context: ..
      args:
        - BUILDER_IMAGE=${BUILDER_IMAGE:-debian}
        - BASE_IMAGE=${BASE_IMAGE:-busybox}
        - GROUP_ID=${GROUP_ID:-1001}
        - USER_ID=${USER_ID:-1001}
    user: runner
    env_file: ../.env
