volumes:
  postgres_data:

services:
  postgres:
    extends:
      file: ./parents.yml
      service: parent
    image: ${POSTGRES_IMAGE}
    user: postgres
    volumes:
      - ../postgres/generate-schema.sql:/docker-entrypoint-initdb.d/50-init.sql:ro
      - ../postgres/generate-users.sh:/docker-entrypoint-initdb.d/60-init.sh:ro
      - postgres_data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
      - BOT_PASSWORD=${BOT_PASSWORD}
      - BOT_USER=${BOT_USER}
      - READER_USER=${READER_USER}
      - READER_PASSWORD=${READER_PASSWORD}
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    networks:
      - default