volumes:
  task-tracker-logs:

services:
  task-tracker:
    extends:
      file: ./parents.yml
      service: custom_service
    build:
      context: ..
      dockerfile: Dockerfile
      target: runner-task-tracker-${PROJECT_BUILD}
    ports:
      - ${TASK_TRACKER_EXTERNAL_PORT}:8080
    volumes:
      - task-tracker-logs:/volumes/logs
    environment:
      - AUTH_KEY=${AUTH_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bot
      - DB_USER=${TASK_TRACKER_USER}
      - DB_PASSWORD=${TASK_TRACKER_PASSWORD}
      - LISTEN_IP=0.0.0.0
      - LISTEN_PORT=8080
      - LOGS_PATH=/volumes/logs
      - BOT_URL=http://bot:8080