volumes:
  web_server_files:

services:
  web_server:
    extends:
      file: ./parents.yml
      service: parent
    image: ${WEB_SERVER_IMAGE:-nginx:1.26.3-alpine}
    user: nginx
    volumes:
      - ./web_server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web_server/ssl:/etc/nginx/ssl/:ro
      - ./web_server/html:/html/.html:ro
      - web_server_files:/uploads:ro
    ports:
      - ${WEB_SERVER_EXTERNAL_PORT:-0.0.0.0:443}:443