volumes:
  youtube_api_venv:
  youtube_api_logs:

services:
  youtube_api:
    extends:
      file: parents.yml
      service: python_service
    ports:
      - ${YOUTUBE_API_EXTERNAL_PORT}:8080
    working_dir: /volumes/
    environment:
      - BOT_URL=http://bot:8080
      - SELENIUM_HOST=http://selenium:4444/wd/hub
      - SELENIUM_PAGE_LOAD_TIME=${YOUTUBE_API_SELENIUM_PAGE_LOAD_TIME}
      - TEST_YOUTUBE_VIDEO=${YOUTUBE_API_TEST_YOUTUBE_VIDEO}
      - GOOGLE_EMAIL=${GOOGLE_EMAIL}
      - GOOGLE_PASSWORD=${GOOGLE_PASSWORD}
      - USE_OAUTH=${USE_OAUTH}
    volumes:
      - youtube_api_venv:/volumes/venv
      - youtube_api_logs:/volumes/logs
      - ../youtube_api:/volumes/app:ro