function(create_unity_build_target target_name sources_var output_file)
    set(sources ${${sources_var}})
    set(unity_dir "${CMAKE_BINARY_DIR}/unity/${target_name}")
    file(MAKE_DIRECTORY "${unity_dir}")
    
    set(unity_file "${unity_dir}/${output_file}")
    
    set(unity_content "// Unity build file for ${target_name}\n// Auto-generated by CMake\n\n")
    foreach(source_file ${sources})
        get_filename_component(abs_source "${source_file}" ABSOLUTE)
        string(APPEND unity_content "#include \"${abs_source}\"\n")
    endforeach()
    
    set(temp_file "${unity_file}.tmp")
    file(WRITE "${temp_file}" "${unity_content}")
    
    execute_process(
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${temp_file}"
        "${unity_file}"
    )
    
    file(REMOVE "${temp_file}")
    
    set(${sources_var} "${unity_file}" PARENT_SCOPE)
endfunction()