#!/bin/bash
set -e

echo "
    CREATE USER $BOT_USER WITH PASSWORD '$BOT_PASSWORD';
    GRANT SELECT, INSERT, UPDATE ON TABLE
        users, user_screens, 
        chats, chat_types, 
        messages, message_content_types,
        callbacks,
        api_requests, api_request_services,
        accesses, access_types
    TO $BOT_USER;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $BOT_USER;
    CREATE ROLE $READER_USER WITH
        LOGIN
        NOSUPERUSER
        NOINHERIT
        NOCREATEDB
        NOCREATEROLE
        NOREPLICATION
        PASSWORD '$READER_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $READER_USER;
    GRANT USAGE ON SCHEMA public TO $READER_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $READER_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $READER_USER;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $READER_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $READER_USER;
" \
| psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"