name: publish-bot-image
on:
  [workflow_dispatch]

jobs:
  publish-bot:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-images
        run: |
          docker build . --target runner-bot-debug --build-arg BUILDER_IMAGE=ubuntu:latest --build-arg RUNNER_IMAGE=ubuntu:latest -t ghcr.io/kologermit/cpp-keber/bot:debug-ubuntu
          docker build . --target runner-bot-release --build-arg BUILDER_IMAGE=ubuntu:latest --build-arg RUNNER_IMAGE=ubuntu:latest -t ghcr.io/kologermit/cpp-keber/bot:release-ubuntu
          docker build . --target runner-bot-debug --build-arg BUILDER_IMAGE=alpine:latest --build-arg RUNNER_IMAGE=alpine:latest -t ghcr.io/kologermit/cpp-keber/bot:debug-alpine
          docker build . --target runner-bot-release --build-arg BUILDER_IMAGE=alpine:latest --build-arg RUNNER_IMAGE=alpine:latest -t ghcr.io/kologermit/cpp-keber/bot:release-alpine
      - name: publish-image
        run: |
          docker login --username kologermit --password ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }} ghcr.io
          docker push ghcr.io/kologermit/cpp-keber/bot:debug-ubuntu
          docker push ghcr.io/kologermit/cpp-keber/bot:release-ubuntu
          docker push ghcr.io/kologermit/cpp-keber/bot:debug-alpine
          docker push ghcr.io/kologermit/cpp-keber/bot:release-alpine
  publish-task-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-images
        run: |
          docker build . --target runner-task-tracker-debug --build-arg BUILDER_IMAGE=ubuntu:latest --build-arg RUNNER_IMAGE=ubuntu:latest -t ghcr.io/kologermit/cpp-keber/task-tracker:debug-ubuntu
          docker build . --target runner-task-tracker-release --build-arg BUILDER_IMAGE=ubuntu:latest --build-arg RUNNER_IMAGE=ubuntu:latest -t ghcr.io/kologermit/cpp-keber/task-tracker:release-ubuntu
          docker build . --target runner-task-tracker-debug --build-arg BUILDER_IMAGE=alpine:latest --build-arg RUNNER_IMAGE=alpine:latest -t ghcr.io/kologermit/cpp-keber/task-tracker:debug-alpine
          docker build . --target runner-task-tracker-release --build-arg BUILDER_IMAGE=alpine:latest --build-arg RUNNER_IMAGE=alpine:latest -t ghcr.io/kologermit/cpp-keber/task-tracker:release-alpine
      - name: publish-image
        run: |
          docker login --username kologermit --password ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }} ghcr.io
          docker push ghcr.io/kologermit/cpp-keber/task-tracker:debug-ubuntu
          docker push ghcr.io/kologermit/cpp-keber/task-tracker:release-ubuntu
          docker push ghcr.io/kologermit/cpp-keber/task-tracker:debug-alpine
          docker push ghcr.io/kologermit/cpp-keber/task-tracker:release-alpine

